### ISSUE TITLE
Encountered image distortion after reading with `slide.read_region()`

### ISSUE THREAD

**Issue by super233** [openslide/openslide-python#102] opened 2020-10-29 03:53 UTC
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Ubuntu 18.04.3 LTS
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 1.1.2
**OpenSlide version** (`openslide.__library_version__`): 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): TIF

## Details
Encountered image distortion after reading with `slide.read_region()`, is there any solutions?

![image](https://user-images.githubusercontent.com/35358984/97523300-d8755600-19dc-11eb-8b5c-23ad7f8e7ff9.png)

**Comment by bgilbert** [comment] 2020-10-29 03:56
There is no OpenSlide or OpenSlide Python version 3.7.3.  Please double-check your OpenSlide version.

Is this a generic tiled TIFF image, or is it produced by a particular scanner vendor?

**Comment by super233** [comment] 2020-10-29 07:56
When I use python 3.6, this problem has been solved. Thank you for your reply.

**Comment by jaharkes** [comment] 2020-10-29 13:41
Was this an observed problem when using python 3.7.3 as the interpreter then?

**Comment by super233** [comment] 2020-10-29 13:51
Do you mean that the problem was not reported in openslide when runing with python 3.7.3, but oberved after the target file generated? @jaharkes

**Comment by jaharkes** [comment] 2020-10-29 15:06
I was just curious because the original bug report mentioned openslide-python-3.7.3 which is something that doesn't exist.
And then you closed it with a comment that when you use python-3.6 the problem is solved.

So I was trying to figure out if the original report was about python-3.7.3 instead.

**Comment by super233** [comment] 2020-10-29 15:21
Ooops, sorry! The original report was about python-3.7.3! I have updated the issue description.

**Comment by bgilbert** [comment] 2022-05-29 01:04
It's possible that this is caused by a bug in old versions of pixman.  Are you still seeing this issue?

**Comment by bgilbert** [comment] 2024-09-07 04:12
This issue may have been caused by https://github.com/openslide/openslide/issues/278.  I'll close, but feel free to comment here or open a new issue if you're still seeing this.

**Closed by bgilbert** 2024-09-07 04:12 UTC
