### ISSUE TITLE
mportError: cannot import name '_convert' from partially initialized module 'openslide' (most likely due to a circular import) (H:\openslide-python\openslide\__init__.py)

### ISSUE THREAD

**Issue by kohinur-jk** [openslide/openslide-python#138] opened 2021-08-25 03:03 UTC
>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "H:\openslide-python\openslide\__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "H:\openslide-python\openslide\lowlevel.py", line 49, in <module>
    from . import _convert
ImportError: cannot import name '_convert' from partially initialized module 'openslide' (most likely due to a circular import) (H:\openslide-python\openslide\__init__.py)

**Comment by bgilbert** [comment] 2021-08-25 03:04
Duplicate of https://github.com/openslide/openslide-python/issues/124.

**Closed by bgilbert** 2021-08-25 03:04 UTC
