### ISSUE TITLE
read_region returns black/stripy image when reading pyramidal tiffs at level > 0

### ISSUE THREAD

**Issue by tamkaho** [openslide/openslide-python#71] opened 2020-01-30 14:16 UTC
## Context

**Issue type**: bug report
**Operating system**: Ubuntu 18.04
**Platform**:  64-bit x86
**OpenSlide Python version** : 1.1.1
**OpenSlide version** :  3.4.1
**Slide format** tiff

## Details
I've created some pyramidal tiffs using different methods. However, when reading a slide using read_region(), I keep getting black / stripy images at levels other than 0.

I've tried creating the tiffs with:
- different compression methods: jpeg, no-compression, lzw, deflate
- different conversion libraries: vips (8.4.5) / imagemagick (version: 6.9.7-4)
(As adviced here: https://github.com/openslide/openslide/wiki/CreatingPyramidalTIFFs)

For  `img = slide.read_region((x,y), level, (w,h))`, black/stripy images usually occurs when x>0 or y >0. But in some cases they could also occur when x=0,y=0.

**Comment by tamkaho** [comment] 2020-01-30 14:35
After reading another post with similar issues (I have black images instead):
https://github.com/openslide/openslide-python/issues/62

I've tried installing the newest pixman version (0.38) but the issue still persists.
I can't install pixmann=0.36 due to conflicts with other libraries.

**Comment by YoniSchirris** [comment] 2020-04-21 11:11
@tamkaho did you manage to fix these dependencies? If so, I'd love to hear your solution.

If not, v0.40.0 has been released three days ago, and conda should be updated soon. You can follow a discussion in https://github.com/libvips/libvips/issues/1401

**Comment by JiayunLi** [comment] 2020-04-30 18:17
I encountered the similar problem when I upgraded to Python 3.6.

**Comment by AshishRMenon** [comment] 2020-07-01 12:40
Hello all, I managed to work by reading the slide as PIL image at level 0 and resizing it using the PIL **resize** method by a factor obtained using the '**level_downsamples**' for the respective level. The black region doesn't seem to occur using this method.

**Comment by bgilbert** [comment] 2020-09-13 05:07
I'll close this as a duplicate of https://github.com/openslide/openslide-python/issues/62.  If you're still seeing this with a fixed version of pixman, feel free to reopen.

**Closed by bgilbert** 2020-09-13 05:07 UTC
