### ISSUE TITLE
OpenSlideUnsupportedFormatError: Unsupported or missing image file

### ISSUE THREAD

**Issue by joelvis-maker** [openslide/openslide-python#105] opened 2020-11-27 15:31 UTC
## Context
Issue type: Feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): Python version: 1.1.1
**OpenSlide version** (`openslide.__library_version__`): Python version: 1.1.1
**Slide format** (e.g. SVS, NDPI, MRXS): bif

## Details

When I import some images I get this error:
```
slide = ops.OpenSlide('img.bif')

/usr/local/lib/python3.6/dist-packages/openslide/lowlevel.py in _check_open(result, _func, _args)
    127     if result is None:
    128         raise OpenSlideUnsupportedFormatError(
--> 129                 "Unsupported or missing image file")
    130     slide = _OpenSlide(c_void_p(result))
    131     err = get_error(slide)

OpenSlideUnsupportedFormatError: Unsupported or missing image file
```

**Comment by bgilbert** [comment] 2020-11-27 20:01
Closing as duplicate of https://github.com/openslide/openslide/issues/318.

**Closed by bgilbert** 2020-11-27 20:01 UTC
Labels: invalid
