### ISSUE TITLE
openslide fails to import with: cannot import name '_convert' from partially initialized module 'openslide'

### ISSUE THREAD

**Issue by kiranvaidhya** [openslide/openslide-python#124] opened 2021-06-01 09:53 UTC
## Context

**Issue type**: bug, openslide fails to import 
**Operating system**: Windows 10
**Platform**: Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] on win32 
**OpenSlide Python version** (`openslide.__version__`): 1.1.2
**OpenSlide version** (`openslide.__library_version__`): Unknown as I am unable to import

## Details
I am running it in an Anaconda environment in Windows 10.
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.18.1
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] on win32
```
The traceback is available here for your reference
```python
import openslide

Traceback (most recent call last):
  File "C:\Users\kiran\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-bb94c1b557c7>", line 1, in <module>
    import openslide
  File "D:\Programs\PyCharm 2020.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\kiran\Anaconda3\lib\site-packages\openslide\__init__.py", line 35, in <module>
    from openslide import lowlevel
  File "D:\Programs\PyCharm 2020.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\kiran\Anaconda3\lib\site-packages\openslide\lowlevel.py", line 40, in <module>
    from . import _convert
ImportError: cannot import name '_convert' from partially initialized module 'openslide' (most likely due to a circular import) (C:\Users\kiran\Anaconda3\lib\site-packages\openslide\__init__.py)
```

**Comment by jaharkes** [comment] 2021-06-01 15:51
Something went wrong when you installed openslide-python, the missing `openslide._convert` module is a binary extension that is normally installed by pip from the pre-built binary wheel packages. When you build from source, it should have been compiled during installation, but that requires having an installed C compiler on your system.

**Comment by bgilbert** [comment] 2021-06-14 00:00
Tentatively closing as not a bug in OpenSlide Python.  If you have additional information for us to consider, please feel free to reopen.

**Closed by bgilbert** 2021-06-14 00:00 UTC
Labels: invalid

**Comment by gigony** [comment] 2021-06-30 23:43
@kiranvaidhya There is an issue with conda package and it seems that openslide conda packages don't support Windows yet.

https://github.com/conda-forge/openslide-python-feedstock/issues/4

**Comment by birm** [comment] 2023-06-29 18:50
For informative purposes, this error also occurs when you try to import openslide while pwd is clone of this repository.
