### ISSUE TITLE
"OpenSlideError: Cannot read slide position info: Expected 1 value" opening MIRAX data

### ISSUE THREAD

**Issue by VanishingRasengan** [openslide/openslide-python#159] opened 2022-05-29 10:13 UTC
## Context

**Issue type**: compatibility 
**Operating system** : Windows 11, Google Colab
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86, Google Colab
**OpenSlide Python version**:  openslide-python-1.1.2
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

## Details

Dear Openslide Python,

first of all I want to say thank you for developing and maintaining this unique interface for reading virtual slides!
However, I have a problem when it comes to open MRXS files with Openslide. I know that MRXS is a very problematic format and there are lots of discussions around it but unfortunately I have lots of scanned slides in this format and I am desperately trying to make use of them...

I use OpenSlide on Google Colab and used the following code:

```
from openslide import open_slide
import openslide
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt

path= './drive/MyDrive/DigitalSlide_E10M_2S_1_10-6-2021_04-31-03.mrxs'
slide = open_slide(path)
```

In the end I get the following error:

```
---------------------------------------------------------------------------

OpenSlideError                            Traceback (most recent call last)

<ipython-input-24-41a0213c9dad> in <module>()
      1 path= './drive/MyDrive/DigitalSlide_E10M_2S_1_10-6-2021_04-31-03.mrxs'
----> 2 slide = open_slide(path)

2 frames

/usr/local/lib/python3.7/dist-packages/openslide/__init__.py in open_slide(filename)
    386     object for other types of images."""
    387     try:
--> 388         return OpenSlide(filename)
    389     except OpenSlideUnsupportedFormatError:
    390         return ImageSlide(filename)

/usr/local/lib/python3.7/dist-packages/openslide/__init__.py in __init__(self, filename)
    158         AbstractSlide.__init__(self)
    159         self._filename = filename
--> 160         self._osr = lowlevel.open(filename)
    161 
    162     def __repr__(self):

/usr/local/lib/python3.7/dist-packages/openslide/lowlevel.py in _check_open(result, _func, _args)
    131     err = get_error(slide)
    132     if err is not None:
--> 133         raise OpenSlideError(err)
    134     return slide
    135 

OpenSlideError: Cannot read slide position info: Expected 1 value
```

I have already seen some ideas to make it work like converting MRXS to MRXS with the SlideMaster software but I does not work anymore. Is there any solution to tackle this problem?

**Comment by NeelKanwal** [comment] 2022-05-29 18:57
I also have a problem working with the MRXS format. I am actually using HistoLab to create patches from a WSI but it relies on OpenSlide. I am currently using Openslide 1.1.2.

This is how it appears when I try to load the slide. 
img = openslide.OpenSlide(PATH_TO_SLIDE)

![image](https://user-images.githubusercontent.com/52494244/170885649-7fe40aa4-9873-4c52-b52f-cbde6d558713.png)

with histolab
![image](https://user-images.githubusercontent.com/52494244/170885658-a92806d8-3c0d-43d8-bca9-e492b50be934.png)

However it works fine when I try to load the same WSI using Pyvips: 
current_img_400x = vips.Image.new_from_file(os.path.join(directory, fname), level=0, autocrop=True)

It is really strange as I tried to change the versions of openslide-python but the problem is same.

Anyone has similar problem or any suggestions?

**Comment by bgilbert** [comment] 2022-05-29 21:07
@VanishingRasengan This is a known problem; see https://github.com/openslide/openslide/issues/251.  Your slides are triggering a safety check inside OpenSlide.  If you're up for it, you could try deleting the check and see whether the slides appear to read correctly.  If you try this, please post your results in the OpenSlide bug linked above.  I'll go ahead and close this as a duplicate issue.

@NeelKanwal Please don't reuse existing bugs for unrelated problems.  The black background strongly suggests that HistoLab [does not correctly handle premultiplied alpha](https://github.com/openslide/openslide/wiki/PremultipliedARGB).

**Closed by bgilbert** 2022-05-29 21:07 UTC
