### ISSUE TITLE
can not install openslide-python on mac os 10.14

### ISSUE THREAD

**Issue by Sadegh-Saberian** [openslide/openslide-python#79] opened 2020-04-03 23:18 UTC
hi,
I am trying to install open-slide on my mac os 10.14 but i get the following error:
```
Collecting openslide-python
  Downloading openslide-python-1.1.1.tar.gz (312 kB)
     |████████████████████████████████| 312 kB 1.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3r/v3p2m8ws7bjb667hn40t_y300000gn/T/pip-install-t4flc9lh/openslide-python/setup.py'"'"'; __file__='"'"'/private/var/folders/3r/v3p2m8ws7bjb667hn40t_y300000gn/T/pip-install-t4flc9lh/openslide-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3r/v3p2m8ws7bjb667hn40t_y300000gn/T/pip-install-t4flc9lh/openslide-python/pip-egg-info
         cwd: /private/var/folders/3r/v3p2m8ws7bjb667hn40t_y300000gn/T/pip-install-t4flc9lh/openslide-python/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3r/v3p2m8ws7bjb667hn40t_y300000gn/T/pip-install-t4flc9lh/openslide-python/setup.py", line 2, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
I would appreciate if you could let me know how can i fix it.
thanks!

**Comment by Borda** [comment] 2020-04-08 22:00
it happens also on Linux, https://app.circleci.com/pipelines/github/Borda/BIRL/876/workflows/bcb88e49-13e9-4c08-aef8-32574aa459b1/jobs/2384

**Comment by Borda** [comment] 2020-04-08 22:07
it seems to be a problem with `setuptools` for me v41.x work fine but v46.x crashes

**Comment by christophelec** [comment] 2020-04-09 16:40
It seems setuptools had a long plan to remove Features, and removed it in 46.0 : https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4600

Forcinf the install of setuptools v45.3.0 beforehand can be used as a temporary workaround

**Comment by lucabordo** [comment] 2020-04-29 17:41
There is a pull request https://github.com/openslide/openslide-python/pull/76 that seems to fix the setuptools issues? 

The issue is perhaps whether there is still active maintenance of this project, and a process for anyone to accept this merge request?

**Comment by alessiamarcolini** [comment] 2020-06-20 12:03
Dear everyone, as a gesture of courtesy towards the community, we forked the openslide-python repo and we released it on PyPI. Please note that this is a **temporary workaround** to have openslide-python installable via pip without the setuptools issue.

https://pypi.org/project/openslide-wrapper/1.1.2/

cc @ernestoarbitrio and @nicolebussola

**Comment by bgilbert** [comment] 2020-09-13 04:11
Duplicate of #80.

**Closed by bgilbert** 2020-09-13 04:11 UTC
