### ISSUE TITLE
OpenSlideError: Bad direction attribute "LEFT"

### ISSUE THREAD

**Issue by JonyJiang123** [openslide/openslide-python#253] opened 2023-12-28 06:53 UTC
### Operating system

windows11

### Platform

64x86

### OpenSlide Python version

1.3.1

### OpenSlide version

4.0.0

### Slide format

bif

### Issue details

Traceback (most recent call last):

  Cell In[6], line 1
    slide = OpenSlide(r'D:\Jony\Project\Read_Tiff\data\Ventana-1.bif')

  File ~\miniconda3\lib\site-packages\openslide\__init__.py:179 in __init__
    self._osr = lowlevel.open(str(filename))

  File ~\miniconda3\lib\site-packages\openslide\lowlevel.py:207 in _check_open
    raise OpenSlideError(err)

OpenSlideError: Bad direction attribute "LEFT"

**Comment by bgilbert** [comment] 2023-12-28 06:55
Duplicate of https://github.com/openslide/openslide/issues/234.

**Closed by bgilbert** 2023-12-28 06:55 UTC
Labels: defect
